#!/usr/bin/env bash
# Build and install the agent-runner thin execution adapter to a stable
# absolute path so Codex Rules can allow it by prefix.
#
#   install.sh            # frozen snapshot install (recommended)
#   install.sh --symlink  # live symlink to the repo (development)
#
# Both modes build the TypeScript to dist/ first. Frozen install copies dist/
# to ~/.local/share/agent-runner and writes a frozen launcher to
# ~/.local/bin/agent-runner pinned to that snapshot, so repo updates do NOT
# change the privileged entry until you re-install. The symlink install links
# the live repo, so edits take effect after the next build (development only).

set -euo pipefail

MODE="snapshot"
if [[ "${1:-}" == "--symlink" ]]; then
  MODE="symlink"
elif [[ -n "${1:-}" ]]; then
  echo "Unknown argument: $1" >&2
  echo "Usage: install.sh [--symlink]" >&2
  exit 2
fi

SRC_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$HOME/.local/bin"
BIN_PATH="$BIN_DIR/agent-runner"
SHARE_DIR="$HOME/.local/share/agent-runner"

echo "Building TypeScript..."
( cd "$SRC_DIR" && { [[ -d node_modules ]] || npm install; } && npm run build )

mkdir -p "$BIN_DIR"

if [[ "$MODE" == "symlink" ]]; then
  ln -sf "$SRC_DIR/bin/agent-runner" "$BIN_PATH"
  echo "Symlinked (live) $BIN_PATH -> $SRC_DIR/bin/agent-runner"
else
  rm -rf "$SHARE_DIR"
  mkdir -p "$SHARE_DIR"
  cp -R "$SRC_DIR/dist" "$SHARE_DIR/"
  # Frozen launcher: a real file (not a symlink) pinned to the snapshot path.
  cat > "$BIN_PATH" <<EOF
#!/usr/bin/env node
// Frozen agent-runner launcher. Generated by install.sh; do not edit.
"use strict";
const cli = require("$SHARE_DIR/dist/src/cli.js");
cli.main(process.argv.slice(2))
  .then((code) => process.exit(code))
  .catch((err) => { console.error(err); process.exit(2); });
EOF
  chmod +x "$BIN_PATH"
  echo "Installed frozen snapshot to $SHARE_DIR"
  echo "Wrote frozen launcher to $BIN_PATH"
fi

echo
echo "Next steps:"
echo "  1. Ensure $BIN_DIR is on PATH."
echo "  2. Create an allowlist at ~/.config/agent-runner/allowlist.json"
echo "     (see $SRC_DIR/config/allowlist.example.json)."
echo "  3. Allow only $BIN_PATH in ~/.codex/rules/default.rules:"
echo "       $BIN_PATH print-rules --path $BIN_PATH"
echo "  4. Verify the Codex rule matches:"
echo "       codex execpolicy check --pretty --rules ~/.codex/rules/default.rules -- \\"
echo "         $BIN_PATH run --request /abs/request.json"
